#+TITLE: Org-Mode Primer
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything
#+SETUPFILE: ../theme-bigblow.setup

* Preliminaries
** Basics 
  The third column of [[https://ontologicalblog.files.wordpress.com/2016/12/spacemacs_cheat_sheet_1-22.pdf][this Spacemacs cheat sheet]] has some Org-Mode helps.
  Check it out! 

** Pretty Entities
  There is a STARTUP attribute missing from this file that appears in other
  files you already have: entitiespretty

  If you include it, when you visit this file you will start up in the *entities
  pretty* display mode. Otherwise, you will see the \ldquo{}ORG entity\rdquo as a backslash
  (\) followed by the name of a symbol.

  If you type Control-C (C-c) followed by Control-x (C-x) followed by the
  backslash (\) character, you will run the

  =org-toggle-pretty-entities=

  command. Of course,

  =SPC SPC org-toggle-pretty-entities=

  will also invoke it, but at the cost of more typing.

*** Warmup
  Try it: C-c C-x \

  then remove each of the spaces that just follow the four backslashes below to
  see how they change to a symbol.

  \ sum

  \ prod

  \ forall

  \ exists

  (Type the u character four times to undo those four deletions.)

** Subscripts and Superscripts

  To create a subscript, type an underscore (_) character just after a letter or
  word, then the SINGLE character you want as the subscript.

  For example, a _ 1

  typed without the spaces before and after the underscore produces

  a_1

  If you want more than a single character to be the subscript, type an open ({)
  and close (}) curly brace before and after the subscript text.

  For example, type

  node _ { prev }

  without the spaces to see

  node_{prev}

* More symbols and math writing 
  If you remember learning this in a calculus class, great! If not, you
  are not expected to understand it --- just play with the symbols!

  The definition of the limit of a real-valued function *f(x)* of a real
  variable *x* at a point *a* in its domain goes like this:

  lim_{x \rightarrow a} f(x) = L

  means

  \forall \epsilon > 0 \exists \delta > 0 \forall x (0 < |x - a| < \delta \rightarrow |f(x) - L| < \epsilon).

* TODO Create your own table
  Type C-h i (for help info) and scroll down to and hit enter (or click) on the
  Org Mode menu item, and likewise for the Tables menu item under that. Learn
  this powerful magic and you will be amazed at what you can do!

  | Type a backslash (\) |         |
  | followed by          | to see  |
  |----------------------+---------|
  | sum                  | \sum    |
  | prod                 | \prod   |
  | forall               | \forall |
  | exist                | \exist  |
  | ...                  |         |
  | (you fill in         |         |
  | a dozen or so        |         |
  | more rows)           |         |
 
  To help you accomplish this task:
 
  =SPC SPC org-entities-help=

  is your friend.
  
* To See This File Formatted
  [[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
