#+TITLE: Conditional Probability
#+LANGUAGE: en
#+OPTIONS:  H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+STARTUP:  showeverything entitiespretty

* Introduction

  Given the logical equivalence q \rarr r \equiv \not q \lor r, wouldn\rsquo{}t a /conditional/
  probability just be the probability of the union of the effect (consequent)
  with the complement of the cause (antecedent)?

  So, $p(E \rightarrow F)$  $ = p(\overline{E} \cup F)?$

  No! It doesn\rsquo{}t work that way. But we do want to ask, if $E$ occurs, what is
  the probability that $F$ occurs also?

  Here is how it works: if $E$ and $F$ are events in a probability space then
  the conditional probability of $F$ /given/ $E$, which is denoted $p(F \mid
  E)$, is the sum of probabilities of points in both $E$ *and* $F$ divided by
  the sum of probabilities of points in just $E$.

  1. $p(F \mid E) = p(F \cap E)\ /\ p(E)$
  2. $p(E \mid F) = p(E \cap F)\ /\ p(F)$

  The obvious implication of the above two facts, together with the fact that
  set intersection is commutative, is that

  \(p(F \mid E) \cdot p(E) = p(E \mid F) \cdot p(F)\)

  And if $E$ and $F$ are independent events, then

  \(p(F \mid E) = p(F) \text{ and } p(E \mid F) = p(E)\).

* Example --- Roll a Die Twice

  What is the probability of a 3 on the first roll and a 4 on the second roll?

  $E =$ the event of a 3 on the first roll

  Points in $E$: [(3 . 1) (3 . 2) (3 . 3) (3 . 4) (3 . 5) (3 . 6)]

  $F =$ the event of a 4 on the second roll

  Points in $F$: [(1 . 4) (2 . 4) (3 . 4) (4 . 4) (5 . 4) (6 . 4)]

  Points in $F$ and $E$: [(3 . 4)]

  Turn it into a conditional --- what is the probability of a 4 on the second
  roll /given/ a 3 on the first roll?

  $p(F \mid E) = p(F \cap E)\ /\ p(E) = \frac{1/36}{1/6} = \frac{1}{6}$

* *Intuitive* versus *Calculated*

  Draw one card from a 52-card deck:

  $p(\clubsuit \mid Ace\ \clubsuit) = p(\clubsuit \cap Ace\ \clubsuit)\ /\ p(Ace\ \clubsuit) = \frac{1/52}{1/52} = 1$

  $p(\spadesuit \mid Ace\ \heartsuit) = p(\spadesuit \cap Ace\ \heartsuit)\ /\ p(Ace\ \heartsuit) = \frac{0}{1/52} = 0$

  $p(King\ \heartsuit \mid King) =  p(King\ \heartsuit \cap King)\ /\ p(King) = \frac{1/52}{4/52} = \frac{1}{4}$

  $p(\clubsuit \mid Black) = p(\clubsuit \cap Black)\ /\ p(Black) = \frac{13/52}{1/2} = \frac{1/4}{1/2} = \frac{1}{2}$

* General Conjunction Rule

  $p(E \cap F) = p(F) \cdot p(E \mid F) = p(E) \cdot p(F \mid E) = p(F \cap E)$

* More Examples

  Draw two cards in a row (without replacement):

  $p(Ace\ \spadesuit\ \mbox{first} \cap Ace\ \spadesuit\
  \mbox{second}) = p(Ace\ \spadesuit\ \mbox{first}) \cdot p(Ace\
  \spadesuit\ \mbox{second} \mid Ace\ \spadesuit\ \mbox{first}) =
  \frac{1}{52} \cdot 0 = 0$

  $p(\mbox{Red first} \cap \mbox{Red second}) = p(\mbox{Red first})
  \cdot p(\mbox{Red second} \mid \mbox{Red first}) = \frac{1}{2} \cdot
  \frac{25}{51} = \frac{25}{102} < \frac{1}{4} = \frac{1}{2} \cdot
  \frac{1}{2}$

  $p(\mbox{Ace first} \cap \mbox{Ace second}) = p(\mbox{Ace first})
  \cdot p(\mbox{Ace second} \mid \mbox{Ace first}) = \frac{1}{13}
  \cdot \frac{3}{51} = \frac{1}{13} \cdot \frac{1}{17} = \frac{1}{221}
  < \frac{1}{169} = \frac{1}{13} \cdot \frac{1}{13}$

* Independence and the Product Rule

  Recall that independent experiments are when the outcome of one
  experiment does not affect the outcome of others.

  If $p(F \mid E) = p(F)$ then $E$ and $F$ are independent.

  If two independent experiments $E$ and $F$ are carried out in
  sequence, then the probability of both outcomes is $p(E) \cdot p(F)$

  $p(F \mid E) = p(F)$

  $p(F \mid E) = p(F \cap E)\ /\ p(E)$

  $p(F) \cdot p(E) = p(F \cap E)$

  Recall the first example: What is the probability of rolling a 3 and
  then rolling a 4 with a single die?

  $1/6 \cdot 1/6 = 1/36$. These events are independent.

  [[http://setosa.io/conditional/]] is a *very* helpful site for grasping the
  definition and significance of conditional probabilities and independent
  events. See if you agree!
